"""SQLAlchemy ORM models for 살림노트 server."""

import uuid
from datetime import datetime
from sqlalchemy import (
    Boolean, Column, DateTime, Float, Integer, String, ForeignKey, Text
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.utcnow()


class Member(Base):
    __tablename__ = "members"

    id         = Column(String, primary_key=True, default=_uuid)
    username   = Column(String, unique=True, nullable=False, index=True)
    display_name = Column(String, nullable=False)
    hashed_pw  = Column(String, nullable=False)
    role       = Column(String, default="member")   # "admin" | "member"
    invite_code = Column(String, nullable=True)     # code used to join the family
    created_at = Column(DateTime, default=_now)


class FamilyInvite(Base):
    """One-time invite codes generated by admin."""
    __tablename__ = "invites"

    code       = Column(String, primary_key=True)
    created_by = Column(String, ForeignKey("members.id"))
    used_by    = Column(String, ForeignKey("members.id"), nullable=True)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_now)


class MonthlyBudget(Base):
    __tablename__ = "monthly_budgets"

    id               = Column(String, primary_key=True, default=_uuid)
    year             = Column(Integer, nullable=False)
    month            = Column(Integer, nullable=False)
    husband_income   = Column(Float, default=0)
    wife_income      = Column(Float, default=0)
    husband_pocket   = Column(Float, default=0)
    wife_pocket      = Column(Float, default=0)
    note             = Column(Text, default="")
    updated_at       = Column(DateTime, default=_now, onupdate=_now)


class FixedExpense(Base):
    __tablename__ = "fixed_expenses"

    id         = Column(String, primary_key=True, default=_uuid)
    name       = Column(String, nullable=False)
    amount     = Column(Float, default=0)
    category   = Column(String, default="기타")
    note       = Column(Text, default="")
    is_active  = Column(Boolean, default=True)
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)
    deleted    = Column(Boolean, default=False)


class Investment(Base):
    __tablename__ = "investments"

    id             = Column(String, primary_key=True, default=_uuid)
    name           = Column(String, nullable=False)
    type           = Column(String, default="기타")
    monthly_amount = Column(Float, default=0)
    current_value  = Column(Float, default=0)
    note           = Column(Text, default="")
    is_active      = Column(Boolean, default=True)
    created_at     = Column(DateTime, default=_now)
    updated_at     = Column(DateTime, default=_now, onupdate=_now)
    deleted        = Column(Boolean, default=False)


class InstallmentSavings(Base):
    __tablename__ = "installment_savings"

    id             = Column(String, primary_key=True, default=_uuid)
    name           = Column(String, nullable=False)
    target_amount  = Column(Float, default=0)
    monthly_amount = Column(Float, default=0)
    paid_months    = Column(Integer, default=0)
    total_months   = Column(Integer, default=12)
    start_date     = Column(DateTime, default=_now)
    status         = Column(String, default="진행중")
    note           = Column(Text, default="")
    created_at     = Column(DateTime, default=_now)
    updated_at     = Column(DateTime, default=_now, onupdate=_now)
    deleted        = Column(Boolean, default=False)


class TodoItem(Base):
    __tablename__ = "todos"

    id               = Column(String, primary_key=True, default=_uuid)
    title            = Column(String, nullable=False)
    note             = Column(Text, default="")
    is_completed     = Column(Boolean, default=False)
    priority         = Column(Integer, default=1)
    assignee         = Column(String, default="공동")
    category         = Column(String, default="일반")
    due_date         = Column(DateTime, nullable=True)
    reminder_enabled = Column(Boolean, default=False)
    reminder_date    = Column(DateTime, nullable=True)
    completed_at     = Column(DateTime, nullable=True)
    created_at       = Column(DateTime, default=_now)
    updated_at       = Column(DateTime, default=_now, onupdate=_now)
    deleted          = Column(Boolean, default=False)


class Schedule(Base):
    __tablename__ = "schedules"

    id         = Column(String, primary_key=True, default=_uuid)
    title      = Column(String, nullable=False)
    date       = Column(String, nullable=False)   # "YYYY-MM-DD"
    time       = Column(String, nullable=True)    # "HH:MM" or null (all-day)
    all_day    = Column(Boolean, default=True)
    category   = Column(String, default="일반")   # 일반/가족/병원/경조사/기타
    note       = Column(Text, default="")
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)
    deleted    = Column(Boolean, default=False)
