"""routine definitions + stool_count + completer name

Revision ID: 3a54155f8fa6
Revises: 85c577734bda
Create Date: 2026-06-21 00:53:38.633583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a54155f8fa6'
down_revision: Union[str, None] = '85c577734bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('anchor_hour', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_definitions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('neonatal_health_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stool_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_name', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_routine_tasks_definition_id'), ['definition_id'], unique=False)
        # DB 레벨 FK 제약은 생략(이식성). 관계 무결성은 앱/테넌트 스코프가 보장.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_tasks_definition_id'))
        batch_op.drop_column('completed_by_name')
        batch_op.drop_column('definition_id')

    with op.batch_alter_table('neonatal_health_log', schema=None) as batch_op:
        batch_op.drop_column('stool_count')

    with op.batch_alter_table('routine_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_definitions_tenant_id'))

    op.drop_table('routine_definitions')
    # ### end Alembic commands ###
