"""initial schema

Revision ID: 4ac72c16aca3
Revises: 
Create Date: 2026-06-20 10:44:26.917412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac72c16aca3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('temp_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('ix_member_tenant_username', ['tenant_id', 'username'], unique=True)
        batch_op.create_index(batch_op.f('ix_members_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_username'), ['username'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('babies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_babies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('routine_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_invites',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('used_by', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('tenant_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_invites_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('neonatal_health_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('baby_id', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feeding_ml', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('neonatal_health_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_neonatal_health_log_baby_id'), ['baby_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_neonatal_health_log_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neonatal_health_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_neonatal_health_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_neonatal_health_log_baby_id'))

    op.drop_table('neonatal_health_log')
    with op.batch_alter_table('tenant_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_invites_tenant_id'))

    op.drop_table('tenant_invites')
    with op.batch_alter_table('routine_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_tasks_tenant_id'))

    op.drop_table('routine_tasks')
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_babies_tenant_id'))

    op.drop_table('babies')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_tenant_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_username'))
        batch_op.drop_index(batch_op.f('ix_members_tenant_id'))
        batch_op.drop_index('ix_member_tenant_username')

    op.drop_table('members')
    op.drop_table('tenants')
    # ### end Alembic commands ###
